import type { AnatomicalSystem } from "../types/anatomy";

export interface StructureEntry {
  name: string;
  system: AnatomicalSystem;
  position: [number, number, number];
}

/** Static registry of all anatomical structures — powers search & camera fly-to */
export const STRUCTURE_REGISTRY: StructureEntry[] = [
  // ── Skeletal ──────────────────────────────────────────────
  { name: "Pelvic Brim", system: "skeletal", position: [0, 0.45, 0.1] },
  { name: "Iliac Wing (L)", system: "skeletal", position: [-0.95, 0.5, -0.05] },
  { name: "Iliac Wing (R)", system: "skeletal", position: [0.95, 0.5, -0.05] },
  { name: "Sacrum", system: "skeletal", position: [0, 0.85, -0.95] },
  { name: "Coccyx", system: "skeletal", position: [0, -0.05, -0.95] },
  { name: "Pubic Symphysis", system: "skeletal", position: [0, -0.3, 1.3] },
  { name: "Superior Pubic Ramus (L)", system: "skeletal", position: [-0.48, -0.17, 0.9] },
  { name: "Superior Pubic Ramus (R)", system: "skeletal", position: [0.48, -0.17, 0.9] },
  { name: "Inferior Pubic Ramus (L)", system: "skeletal", position: [-0.37, -0.65, 0.93] },
  { name: "Inferior Pubic Ramus (R)", system: "skeletal", position: [0.37, -0.65, 0.93] },
  { name: "Ischium (L)", system: "skeletal", position: [-0.85, -0.55, 0.05] },
  { name: "Ischium (R)", system: "skeletal", position: [0.85, -0.55, 0.05] },
  { name: "Ischial Spine (L)", system: "skeletal", position: [-0.88, -0.3, -0.22] },
  { name: "Ischial Spine (R)", system: "skeletal", position: [0.88, -0.3, -0.22] },
  { name: "Ischial Tuberosity (L)", system: "skeletal", position: [-0.78, -0.95, 0.25] },
  { name: "Ischial Tuberosity (R)", system: "skeletal", position: [0.78, -0.95, 0.25] },
  { name: "Obturator Foramen (L)", system: "skeletal", position: [-0.65, -0.5, 0.65] },
  { name: "Obturator Foramen (R)", system: "skeletal", position: [0.65, -0.5, 0.65] },

  // ── Muscular ──────────────────────────────────────────────
  { name: "Levator Ani", system: "muscular", position: [0, -0.6, 0.05] },
  { name: "Coccygeus (L)", system: "muscular", position: [-0.55, -0.35, -0.6] },
  { name: "Coccygeus (R)", system: "muscular", position: [0.55, -0.35, -0.6] },
  { name: "Piriformis", system: "muscular", position: [-0.15, 0.35, -0.85] },
  { name: "Obturator Internus (L)", system: "muscular", position: [-0.95, -0.55, 0.35] },
  { name: "Obturator Internus (R)", system: "muscular", position: [0.95, -0.55, 0.35] },
  { name: "External Anal Sphincter", system: "muscular", position: [0, -1.0, -0.45] },
  { name: "External Urethral Sphincter", system: "muscular", position: [0, -0.85, 0.65] },
  { name: "Perineal Body", system: "muscular", position: [0, -1.05, 0.05] },
  { name: "Perineal Membrane", system: "muscular", position: [0, -0.95, 0.55] },

  // ── Arterial ──────────────────────────────────────────────
  { name: "Common Iliac Artery (L)", system: "arterial", position: [-0.27, 1.52, -0.38] },
  { name: "Common Iliac Artery (R)", system: "arterial", position: [0.27, 1.52, -0.38] },
  { name: "External Iliac Artery (L)", system: "arterial", position: [-0.8, 0.7, 0.15] },
  { name: "External Iliac Artery (R)", system: "arterial", position: [0.8, 0.7, 0.15] },
  { name: "Internal Iliac Artery (L)", system: "arterial", position: [-0.58, 1.05, -0.43] },
  { name: "Internal Iliac Artery (R)", system: "arterial", position: [0.58, 1.05, -0.43] },
  { name: "Superior Gluteal Artery (L)", system: "arterial", position: [-0.94, 0.6, -0.65] },
  { name: "Superior Gluteal Artery (R)", system: "arterial", position: [0.94, 0.6, -0.65] },
  { name: "Lateral Sacral Artery (L)", system: "arterial", position: [-0.41, 0.5, -0.8] },
  { name: "Iliolumbar Artery (L)", system: "arterial", position: [-0.83, 1.15, -0.26] },
  { name: "Uterine Artery (L)", system: "arterial", position: [-0.37, 0.4, -0.18] },
  { name: "Uterine Artery Ascending (L)", system: "arterial", position: [-0.17, 0.2, 0.17] },
  { name: "Uterine Artery (R)", system: "arterial", position: [0.37, 0.4, -0.18] },
  { name: "Uterine Artery Ascending (R)", system: "arterial", position: [0.17, 0.2, 0.17] },
  { name: "Superior Vesical Artery (L)", system: "arterial", position: [-0.4, 0.43, 0.08] },
  { name: "Vaginal Artery (L)", system: "arterial", position: [-0.19, -0.25, 0.2] },
  { name: "Obturator Artery (L)", system: "arterial", position: [-0.72, 0.15, 0.16] },
  { name: "Middle Rectal Artery (L)", system: "arterial", position: [-0.36, 0.18, -0.52] },
  { name: "Internal Pudendal Artery (L)", system: "arterial", position: [-0.8, 0.15, -0.26] },
  { name: "Internal Pudendal Artery (R)", system: "arterial", position: [0.8, 0.15, -0.26] },
  { name: "Inferior Gluteal Artery (L)", system: "arterial", position: [-0.88, 0.48, -0.63] },
  { name: "Ovarian Artery (L)", system: "arterial", position: [-0.5, 1.2, -0.05] },
  { name: "Ovarian Artery (R)", system: "arterial", position: [0.5, 1.2, -0.05] },
  { name: "Median Sacral Artery", system: "arterial", position: [0, 0.97, -0.73] },
  { name: "Superior Rectal Artery", system: "arterial", position: [0, 1.22, -0.46] },

  // ── Venous ────────────────────────────────────────────────
  { name: "Internal Iliac Vein (L)", system: "venous", position: [-0.48, 1.08, -0.35] },
  { name: "Internal Iliac Vein (R)", system: "venous", position: [0.48, 1.08, -0.35] },
  { name: "Uterine Venous Plexus", system: "venous", position: [0, 0.1, 0.18] },
  { name: "Presacral Venous Plexus", system: "venous", position: [0, 0.35, -0.94] },
  { name: "Ovarian Vein (L)", system: "venous", position: [-0.46, 1.08, -0.01] },
  { name: "Ovarian Vein (R)", system: "venous", position: [0.46, 1.08, -0.04] },

  // ── Nervous ───────────────────────────────────────────────
  { name: "Sacral Root S1", system: "nervous", position: [-0.25, 0.66, -0.79] },
  { name: "Sacral Root S2", system: "nervous", position: [-0.25, 0.44, -0.79] },
  { name: "Sacral Root S3", system: "nervous", position: [-0.25, 0.22, -0.79] },
  { name: "Sacral Root S4", system: "nervous", position: [-0.25, 0.0, -0.79] },
  { name: "Sacral Root S5", system: "nervous", position: [-0.25, -0.22, -0.79] },
  { name: "Sciatic Nerve (L4-S3)", system: "nervous", position: [-0.84, -0.27, -0.44] },
  { name: "Pudendal Nerve (S2-S4) (L)", system: "nervous", position: [-0.75, -0.28, -0.19] },
  { name: "Pudendal Nerve (S2-S4) (R)", system: "nervous", position: [0.75, -0.28, -0.19] },
  { name: "Obturator Nerve (L2-L4) (L)", system: "nervous", position: [-0.68, 0.33, 0.14] },
  { name: "Obturator Nerve (L2-L4) (R)", system: "nervous", position: [0.68, 0.33, 0.14] },
  { name: "Superior Hypogastric Plexus", system: "nervous", position: [0, 1.25, -0.57] },
  { name: "Hypogastric Nerve (L)", system: "nervous", position: [-0.18, 0.48, -0.43] },
  { name: "Hypogastric Nerve (R)", system: "nervous", position: [0.18, 0.48, -0.43] },
  { name: "Pelvic Splanchnic Nerves (L)", system: "nervous", position: [-0.34, 0.09, -0.43] },
  { name: "Inferior Hypogastric Plexus (L)", system: "nervous", position: [-0.3, -0.15, -0.18] },
  { name: "Inferior Hypogastric Plexus (R)", system: "nervous", position: [0.3, -0.15, -0.18] },

  // ── Lymphatic ─────────────────────────────────────────────
  { name: "External Iliac Nodes", system: "lymphatic", position: [-0.8, 0.7, 0.1] },
  { name: "Obturator Nodes", system: "lymphatic", position: [-0.74, -0.05, 0.53] },
  { name: "Internal Iliac Nodes", system: "lymphatic", position: [-0.58, 0.6, -0.38] },
  { name: "Common Iliac Nodes", system: "lymphatic", position: [-0.3, 1.43, -0.37] },
  { name: "Presacral Nodes", system: "lymphatic", position: [0, 0.35, -0.92] },
  { name: "Para-aortic Nodes", system: "lymphatic", position: [0, 2.23, -0.33] },
  { name: "Superficial Inguinal Nodes", system: "lymphatic", position: [-0.8, -0.4, 1.02] },

  // ── Organs ────────────────────────────────────────────────
  { name: "Uterus", system: "organs", position: [0, -0.15, 0.15] },
  { name: "Cervix", system: "organs", position: [0, -0.4, 0.05] },
  { name: "Vagina", system: "organs", position: [0, -0.55, 0.25] },
  { name: "Urinary Bladder", system: "organs", position: [0, -0.3, 0.85] },
  { name: "Urethra", system: "organs", position: [0, -0.58, 0.75] },
  { name: "Rectum", system: "organs", position: [0, 0.03, -0.6] },
  { name: "Anal Canal", system: "organs", position: [0, -0.88, -0.43] },
  { name: "Ovary (L)", system: "organs", position: [-0.68, 0.28, 0.18] },
  { name: "Ovary (R)", system: "organs", position: [0.68, 0.28, 0.18] },
  { name: "Fallopian Tube (L)", system: "organs", position: [-0.47, 0.44, 0.17] },
  { name: "Fallopian Tube (R)", system: "organs", position: [0.47, 0.44, 0.17] },
  { name: "Fimbriae (L)", system: "organs", position: [-0.65, 0.32, 0.2] },
  { name: "Fimbriae (R)", system: "organs", position: [0.65, 0.32, 0.2] },
  { name: "Ureter (L)", system: "organs", position: [-0.36, 0.45, 0.13] },
  { name: "Ureter (R)", system: "organs", position: [0.36, 0.45, 0.13] },

  // ── Fascia & Ligaments ────────────────────────────────────
  { name: "Cardinal Ligament (L)", system: "fascia", position: [-0.35, -0.05, 0.05] },
  { name: "Cardinal Ligament (R)", system: "fascia", position: [0.35, -0.05, 0.05] },
  { name: "Uterosacral Ligament (L)", system: "fascia", position: [-0.15, 0.15, -0.45] },
  { name: "Uterosacral Ligament (R)", system: "fascia", position: [0.15, 0.15, -0.45] },
  { name: "Round Ligament (L)", system: "fascia", position: [-0.65, 0.2, 0.65] },
  { name: "Round Ligament (R)", system: "fascia", position: [0.65, 0.2, 0.65] },
  { name: "Sacrospinous Ligament (L)", system: "fascia", position: [-0.52, -0.15, -0.56] },
  { name: "Sacrospinous Ligament (R)", system: "fascia", position: [0.52, -0.15, -0.56] },
  { name: "Sacrotuberous Ligament (L)", system: "fascia", position: [-0.5, -0.35, -0.4] },
  { name: "Sacrotuberous Ligament (R)", system: "fascia", position: [0.5, -0.35, -0.4] },
  { name: "Broad Ligament (L)", system: "fascia", position: [-0.35, 0.15, 0.15] },
  { name: "Broad Ligament (R)", system: "fascia", position: [0.35, 0.15, 0.15] },
  { name: "Infundibulopelvic Ligament (L)", system: "fascia", position: [-0.9, 0.55, -0.08] },
  { name: "Infundibulopelvic Ligament (R)", system: "fascia", position: [0.9, 0.55, -0.08] },

  // ── Pelvic Spaces ─────────────────────────────────────────
  { name: "Retropubic Space (Space of Retzius)", system: "spaces", position: [0, 0.1, 1.13] },
  { name: "Vesicovaginal Space", system: "spaces", position: [0, -0.3, 0.55] },
  { name: "Rectovaginal Space", system: "spaces", position: [0, -0.35, -0.2] },
  { name: "Pouch of Douglas (Rectouterine Pouch)", system: "spaces", position: [0, 0.05, -0.2] },
  { name: "Pararectal Space (L)", system: "spaces", position: [-0.55, -0.05, -0.35] },
  { name: "Pararectal Space (R)", system: "spaces", position: [0.55, -0.05, -0.35] },
  { name: "Paravesical Space (L)", system: "spaces", position: [-0.6, -0.05, 0.6] },
  { name: "Paravesical Space (R)", system: "spaces", position: [0.6, -0.05, 0.6] },
  { name: "Presacral Space", system: "spaces", position: [0, 0.35, -0.95] },
  { name: "Ischioanal Fossa (L)", system: "spaces", position: [-0.55, -0.85, -0.1] },
  { name: "Ischioanal Fossa (R)", system: "spaces", position: [0.55, -0.85, -0.1] },
  { name: "Vesicouterine Pouch", system: "spaces", position: [0, 0.1, 0.5] },
  { name: "Obturator Space", system: "spaces", position: [-0.75, -0.1, 0.55] },
];
